name: package test

on: [push]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8.0"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: swift

      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v3

      - name: Build
        run: swift build | xcpretty

      - name: Run tests
        run: swift test | xcpretty

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:swift"

